# Generated by Django 6.0.1 on 2026-01-17 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('surname', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzili')),
                ('message', models.TextField(verbose_name='Yuborilgan xabar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kontakt xabari',
                'verbose_name_plural': 'Kontakt xabarlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
